/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 scene.gltf 
Author: Tomitos (https://sketchfab.com/Tomitos_)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/psx-solar-system-a73b4dd14c6e487d932d233d64437391
Title: PSX Solar System
*/

import React, {  useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'

export default function Model(props) {
  const group = React.useRef()
  const { nodes, materials, animations } = useGLTF('/psx_solar_system/SS1.gltf')
  const { actions,names } = useAnimations(animations, group)


  console.log(names)
const yAxis = new THREE.Vector3(0, 1, 0)
useEffect(() => {
  if (actions["Earth|Planet.009Action"]) {
    actions["Earth|Planet.009Action"].play()
  }
}, [actions])
useEffect(() => {
  const root = group.current
  if (!root) return

  const sun = root.getObjectByName("Sun")
  if (!sun) return

  // 🔥 move entire system so sun is at origin
  root.position.set(
    -sun.position.x,
    -sun.position.y,
    -sun.position.z
  )
}, [])

useFrame((state, delta) => {
  if (!group.current) return

  const mercuryPivot = group.current.getObjectByName("MercuryPivot");
  // const earthPivot = group.current.getObjectByName("EarthPivot");
  const jupiterPivot = group.current.getObjectByName("JupiterPivot");
  const marsPivot = group.current.getObjectByName("MarsPivot");
  const neptunePivot = group.current.getObjectByName("NeptunePivot");
  const plutoPivot = group.current.getObjectByName("PlutoPivot");
  const saturnPivot = group.current.getObjectByName("SaturnPivot");
  const uranusPivot = group.current.getObjectByName("UranusPivot");
  const venusPivot = group.current.getObjectByName("VenusPivot");
   const earth = group.current.getObjectByName("Earth")

  if (mercuryPivot) {
    mercuryPivot.rotation.y += delta * 1
  }
  // if (earthPivot) {
  //   earthPivot.rotation.y += delta * 0.22
  // }

  if (jupiterPivot) {
    jupiterPivot.rotation.y += delta * 0.25
  }
  if (marsPivot) {
    marsPivot.rotation.y += delta * 0.5
  }
  if (neptunePivot) {
    neptunePivot.rotation.y += delta * 0.11
  }
  if (plutoPivot) {
    plutoPivot.rotation.y += delta * 0.6
  }
  if (saturnPivot) {
    saturnPivot.rotation.y += delta * 0.2
  }
  if (uranusPivot) {
    uranusPivot.rotation.y += delta * 0.15
  }
  if (venusPivot) {
    venusPivot.rotation.y += delta * 1
  }
  
  
  // if (earth) {
  //   earth.rotateOnWorldAxis(yAxis, delta * 0.5)
  // }
// const moonOrbit = group.current.getObjectByName("MoonOrbit")

// if (moonOrbit) {
//   moonOrbit.rotation.y += delta * 3
// }
})



function Orbit({ radius }) {
  const points = []

  for (let i = 0; i <= 100; i++) {
    const angle = (i / 100) * Math.PI * 2
    points.push(
      new THREE.Vector3(
        Math.cos(angle) * radius,
        0,
        Math.sin(angle) * radius
      )
    )
  }

  const geometry = new THREE.BufferGeometry().setFromPoints(points)

  return (
    <line geometry={geometry}>
      <lineBasicMaterial color="white" />
    </line>
  )
}

  return (
    <group ref={group} {...props} dispose={null}>
      <Orbit radius={17.7} />
<Orbit radius={19.5} />
<Orbit radius={23.8} />
<Orbit radius={28} />
<Orbit radius={40} />
<Orbit radius={50} />
<Orbit radius={58.5} />
<Orbit radius={64} />
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="c61b8ace641b4cd8ad723ab77de2df1cfbx" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <group name="Object_2">
              <group name="RootNode">


  <group position={[23.8, 0, 0]}>
   
                <group name="Earth" rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={100}>
                  <mesh name="Earth_earth_0" geometry={nodes.Earth_earth_0.geometry} material={materials.earth} />
               
                
                  <group name="Moon" position={[25.758, 0, 0]}  >
                    <mesh name="Moon_moon_0" geometry={nodes.Moon_moon_0.geometry} material={materials.moon} />
                  </group>
                </group>
                </group>
                




                <group name="JupiterPivot">
                <group name="Jupiter" rotation={[-Math.PI / 2, 0, 0.262]} scale={100}>
                  <mesh name="Jupiter_jupiter_0" geometry={nodes.Jupiter_jupiter_0.geometry} material={materials.jupiter} />
                </group>
                </group>
                <group name="MarsPivot">
                <group name="Mars" rotation={[-Math.PI / 2, 0, Math.PI / 4]} scale={100}>
                  <mesh name="Mars_mars_0" geometry={nodes.Mars_mars_0.geometry} material={materials.mars} />
                </group>
                </group>
                <group name="MercuryPivot">
                <group name="Mercury" rotation={[-Math.PI / 2, 0, 2.356]} scale={100}>
                  <mesh name="Mercury_mercury_0" geometry={nodes.Mercury_mercury_0.geometry} material={materials.mercury} />
                </group>
                </group>
                <group name="NeptunePivot">
                <group name="Neptune" position={[-0.001, 0, -0.001]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={100}>
                  <mesh name="Neptune_neptune_0" geometry={nodes.Neptune_neptune_0.geometry} material={materials.neptune} />
                </group>
                </group>
                <group name="PlutoPivot">
                <group name="Pluto" position={[0, 0, -0.001]} rotation={[-Math.PI / 2, 0, -1.309]} scale={100}>
                  <mesh name="Pluto_pluto_0" geometry={nodes.Pluto_pluto_0.geometry} material={materials.pluto} />
                </group>
                </group>
                <group name="SaturnPivot">
                <group name="Saturn" rotation={[-Math.PI / 2, 0.611, 0]} scale={100}>
                  <group name="SaturnRing" position={[41.778, 0, 29.247]} rotation={[0, -Math.PI / 4, 0]}>
                    <mesh name="SaturnRing_Material_0" geometry={nodes.SaturnRing_Material_0.geometry} material={materials.Material} />
                  </group>
                  <mesh name="Saturn_saturn_0" geometry={nodes.Saturn_saturn_0.geometry} material={materials.saturn} />
                </group>
                </group>
                <group name="Sun" rotation={[-Math.PI / 2, 0, 0]} scale={100}>
                  <mesh name="Sun_sun_0" geometry={nodes.Sun_sun_0.geometry} material={materials.material} />
                </group>
                <group name="UranusPivot">
                <group name="Uranus" rotation={[-Math.PI / 2, 0, -0.436]} scale={100}>
                  <mesh name="Uranus_uranus_0" geometry={nodes.Uranus_uranus_0.geometry} material={materials.uranus} />
                </group>
                </group>
                <group name="VenusPivot">
                <group name="Venus" rotation={[-Math.PI / 2, 0, 1.92]} scale={100}>
                  <mesh name="Venus_venus_0" geometry={nodes.Venus_venus_0.geometry} material={materials.venus} />
                </group>
                </group>
                <group name="Point" rotation={[-0.525, 0.345, 1.306]} scale={200}>
                  <group name="Object_19" rotation={[Math.PI / 2, 0, 0]}>
                    <group name="Object_20" />
                  </group>
                </group>
                <group name="Space" position={[359.942, 0, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={100}>
                  <mesh name="Space_space_0" geometry={nodes.Space_space_0.geometry} material={materials.space} />
                </group>
                
              </group>
              
            </group>
            
          </group>
          
        </group>
        
      </group>
      
    </group>
  )
}

useGLTF.preload('/psx_solar_system/SS1.gltf')
